### ISSUE TITLE
3D gearbox modeling test

### ISSUE THREAD

**Issue by JuanCamilo0509** [JuanCamilo0509/Automatic_Zen_Garden#2]
Print all the bottom case with the straight bevel and test it with a 5v dc motor.

**Comment by josedddd1234** [comment]
NAHHHH I will beter sleep, printing at 9:42

**Comment by josedddd1234** [comment]
Printing at 9:54

**Comment by josedddd1234** [comment]
Printing is done :) 
![1730518464168](https://github.com/user-attachments/assets/b24b4f7f-56f1-4d01-b9d1-9e0cf97b3023)

**Comment by josedddd1234** [comment]
VID SHOWING IT PARTIALLY WORKS
https://github.com/user-attachments/assets/0c85649c-25d1-4cb6-845b-81758d03fdbb
